return {
  -- Wir erweitern die Konfiguration von mason.nvim
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "bash-language-server",
        "beautysh",
        "codebook-lsp",
        "docker-compose-langserver",
        "docker-langserver",
        "docker-language-server",
        "gh",
        "hadolint",
        "htmlhint",
        "lua-language-server",
        "markdownlint-cli2",
        "markdown-toc",
        "marksman",
        "mdformat",
        "pylsp",
        "pyright",
        "pyright-langserver",
        "ruff",
        "shellcheck",
        "shfmt",
        "sqlfluff",
        "stylua",
        "superhtml",
        "systemdlint",
        "systemd-lsp",
        "vscode-css-language-server",
        "vscode-eslint-language-server",
        "vscode-html-language-server",
        "vscode-json-language-server",
        "vtsls",
        "yaml-language-server",
        "yamllint",
      },
    },
  },
}
