return {
  -- Wir erweitern die Konfiguration von mason.nvim
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "bash-language-server",
        "beautysh",
	"black",
        "codebook",
	"css-lsp",
        "docker-compose-language-service",
        "docker-language-server",
        "dockerfile-language-server",
	"eslint-lsp",
	"eslint_d",
        "gh",
        "hadolint",
	"html-lsp",
        "htmlhint",
	"json-lsp",
        "lua-language-server",
        "markdownlint-cli2",
        "markdown-toc",
        "marksman",
        "mdformat",
        "prettier",
        "pyright",
        "python-lsp-server",
        "ruff",
        "shellcheck",
        "shfmt",
        "sqlfluff",
        "stylua",
        "superhtml",
        "systemdlint",
        "systemd-lsp",
        "typescript-language-server",
        "vtsls",
        "yaml-language-server",
        "yamllint",
      },
    },
  },
}
